### ISSUE TITLE
KeyError: 'Poseur is not in the models registry'

### ISSUE THREAD

**Issue by suijua** [aim-uofa/Poseur#17]
**### Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()
  File "tools/train.py", line 175, in main
    model = build_posenet(cfg.model)
  File "/home/wuxl/project/Poseur/mmpose/mmpose/models/builder.py", line 39, in build_posenet
    return POSENETS.build(cfg)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'Poseur is not in the models registry'
Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    main()    main()
  File "tools/train.py", line 175, in main
    model = build_posenet(cfg.model)
  File "/home/wuxl/project/Poseur/mmpose/mmpose/models/builder.py", line 39, in build_posenet
    return POSENETS.build(cfg)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'Poseur is not in the models registry'
Traceback (most recent call last):

  File "tools/train.py", line 175, in main
  File "tools/train.py", line 201, in <module>
    model = build_posenet(cfg.model)
  File "/home/wuxl/project/Poseur/mmpose/mmpose/models/builder.py", line 39, in build_posenet
    return POSENETS.build(cfg)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'Poseur is not in the models registry'
    main()
  File "tools/train.py", line 175, in main
    model = build_posenet(cfg.model)
  File "/home/wuxl/project/Poseur/mmpose/mmpose/models/builder.py", line 39, in build_posenet
    return POSENETS.build(cfg)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'Poseur is not in the models registry'
Killing subprocess 225662
Killing subprocess 225663
Killing subprocess 225664
Killing subprocess 225665
Traceback (most recent call last):
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/wuxl/anaconda3/envs/pytorch/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/poseur/coco/poseur_res50_coco_256x192.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/poseur_res50_coco_256x192']' returned non-zero exit status 1.
(pytorch) wuxl@sitonholy:~/project/Poseur$ 

Hi! I train the model  by **bash tools/dist_train.sh configs/poseur/coco/poseur_res50_coco_256x192.py 4 --work-dir work_dirs/poseur_res50_coco_256x192** ,but here get something wrong  as the above, can you help me ,thank you!

**Comment by YongtaoGe** [comment]
@suijua It seems that you do not install the package correctly.

**Comment by suijua** [comment]
> package correctly

Yes, I install the MMpose  package again, this problem is solved. thanks for you!

**Comment by pengzhansun** [comment]
> > package correctly
> 
> Yes, I install the MMpose package again, this problem is solved. thanks for you!

Hi suijua, may I know how you solve this problem? I encountered with the same error. I try to download the mmpose==0.28.0, but the link for this version on the official doc is invalid.

**Comment by suijua** [comment]
> > > package correctly
> > 
> > 
> > Yes, I install the MMpose package again, this problem is solved. thanks for you!
> 
> Hi @suijua , may I know how you solve this problem? I encountered with the same error. I try to download the mmpose==0.28.0, but the link for this version on the official doc is invalid.

you can copy the models (https://github.com/aim-uofa/Poseur/tree/main/mmpose/models) to MMpose package(mmpose/mmpose/models) you downloard
